apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    {{- include "chartapigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
  {{ end }}  
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http

  {{- if .Values.prometheusService.enabled }}
    - port: {{ .Values.prometheusService.port }}
  {{ if eq .Values.prometheusService.type "NodePort" }}
      nodePort: {{ .Values.prometheusService.nodePort }}
  {{ end }}  
      targetPort: {{ .Values.prometheusService.port }}
      protocol: TCP
      name: {{ .Values.prometheusService.name }}
  {{- end }}

  selector:
    {{- include "chartapigw.selectorLabels" . | nindent 4 }}
