apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabels.app }}
  labels:
    {{- include "chartapigw.labels" . | nindent 4 }}
    app: {{ .Values.appLabels.app }}
    project: {{ .Values.appLabels.project }}
    role: {{ .Values.appLabels.type }}
    env: {{ .Values.appLabels.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
  {{ end }}  
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http

  {{- if .Values.prometheusService.enabled }}
    - port: {{ .Values.prometheusService.port }}
  {{ if eq .Values.prometheusService.type "NodePort" }}
      nodePort: {{ .Values.prometheusService.nodePort }}
  {{ end }}  
      targetPort: {{ .Values.prometheusService.port }}
      protocol: TCP
      name: {{ .Values.prometheusService.name }}
  {{- end }}

  {{- if .Values.jaegerService.enabled }}
    - port: {{ .Values.jaegerService.port }}
  {{ if eq .Values.jaegerService.type "NodePort" }}
      nodePort: {{ .Values.jaegerService.nodePort }}
  {{ end }}  
      targetPort: {{ .Values.jaegerService.port }}
      protocol: TCP
      name: {{ .Values.jaegerService.name }}
  {{- end }}
  selector:
    {{- include "chartapigw.selectorLabels" . | nindent 4 }}
